export function openPackagePanel(client,{onChanged=()=>{},onLock=()=>{},pinId=null}={}){
 const dialog=document.createElement('dialog');dialog.className='transaction-dialog';const heading=document.createElement('h2');heading.textContent='Packages / 模块包';dialog.append(heading);
 const note=document.createElement('p');note.textContent='Preview reads the package manifest only. Executable Python plugins run trusted code when explicitly installed; data packages do not install code automatically.';dialog.append(note);
 const file=document.createElement('input');file.type='file';file.accept='.zip';file.setAttribute('aria-label','Package ZIP');dialog.append(file);
 const preview=document.createElement('button');preview.textContent='Preview / 预览';const install=document.createElement('button');install.textContent='Install reviewed package / 安装已预览包';install.disabled=true;dialog.append(preview,install);
 const output=document.createElement('pre');output.className='parameter-record';dialog.append(output);let bytes=null,review=null;
 file.addEventListener('change',()=>{bytes=null;review=null;install.disabled=true;output.textContent='';});
 preview.addEventListener('click',async()=>{try{const selected=file.files[0];if(!selected||selected.size>32*1024*1024)throw Error('Select a ZIP no larger than 32 MiB');const array=new Uint8Array(await selected.arrayBuffer());let binary='';for(let i=0;i<array.length;i+=8192)binary+=String.fromCharCode(...array.subarray(i,i+8192));bytes=btoa(binary);review=await client.request('/api/packages/preview',{archive_base64:bytes});output.textContent=JSON.stringify(review,null,2);install.disabled=false;}catch(error){output.textContent=error.message;install.disabled=true;}});
 install.addEventListener('click',async()=>{if(!review||!bytes)return;install.disabled=true;try{const result=await client.request('/api/packages/install',{archive_base64:bytes,expected_sha256:review.archive_sha256??review.sha256});output.textContent=JSON.stringify(result,null,2);await refresh();await onChanged();}catch(error){output.textContent=error.message;}});
 const installed=document.createElement('section');dialog.append(installed);
 async function refresh(){try{const result=await client.request('/api/packages');installed.replaceChildren();const title=document.createElement('h3');title.textContent='Installed packages';installed.append(title);for(const item of (Array.isArray(result)?result:result.packages??result.installed??[])){const row=document.createElement('div');row.className='task-actions';const label=document.createElement('span');label.textContent=`${item.package?.id??item.id}@${item.package?.version??item.version}`;const remove=document.createElement('button');remove.textContent='Uninstall';remove.addEventListener('click',async()=>{try{output.textContent=JSON.stringify(await client.request('/api/packages/uninstall',{id:item.package?.id??item.id,version:item.package?.version??item.version}),null,2);await refresh();await onChanged();}catch(error){output.textContent=error.message;}});row.append(label,remove);installed.append(row);}}catch(error){output.textContent=error.message;}}
 const requirements=document.createElement('textarea');requirements.value='{}';requirements.setAttribute('aria-label','Exact package requirements JSON');dialog.append(requirements);
 const resolve=document.createElement('button');resolve.textContent='Resolve and pin project lock / 解析项目锁';resolve.addEventListener('click',async()=>{try{const values=JSON.parse(requirements.value);const result=await client.request('/api/packages/resolve',{requirements:values,...(pinId?{pin_id:pinId}:{})});output.textContent=JSON.stringify(result,null,2);await onLock(result);}catch(error){output.textContent=error.message;}});dialog.append(resolve);
 const close=document.createElement('button');close.textContent='Close / 关闭';close.addEventListener('click',()=>dialog.close());dialog.append(close);dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal();refresh();
}
