import {boundedResponseBytes} from './kernel-client.mjs';
import {reviewTransaction} from './transaction-dialog.mjs';
export function openPackagePanel(client,{onChanged=()=>{},onLock=()=>{},onImport=()=>{},pinId=null}={}){
 const dialog=document.createElement('dialog');dialog.className='transaction-dialog';const heading=document.createElement('h2');heading.textContent='Packages / 模块包';dialog.append(heading);
 const note=document.createElement('p');note.textContent='Preview validates the archive without executing code. Install copies verified files only. Executable Python factories run when an explicitly selected project lock is loaded; data files can be downloaded or explicitly imported below.';dialog.append(note);
 const file=document.createElement('input');file.type='file';file.accept='.zip';file.setAttribute('aria-label','Package ZIP');dialog.append(file);
 const preview=document.createElement('button');preview.textContent='Preview / 预览';const install=document.createElement('button');install.textContent='Install reviewed package / 安装已预览包';install.disabled=true;dialog.append(preview,install);
 const output=document.createElement('pre');output.className='parameter-record';dialog.append(output);let bytes=null,review=null;
 file.addEventListener('change',()=>{bytes=null;review=null;install.disabled=true;output.textContent='';});
 preview.addEventListener('click',async()=>{try{const selected=file.files[0];if(!selected||selected.size>32*1024*1024)throw Error('Select a ZIP no larger than 32 MiB');const array=new Uint8Array(await selected.arrayBuffer());let binary='';for(let i=0;i<array.length;i+=8192)binary+=String.fromCharCode(...array.subarray(i,i+8192));bytes=btoa(binary);review=await client.request('/api/packages/preview',{archive_base64:bytes});output.textContent=JSON.stringify(review,null,2);install.disabled=false;}catch(error){output.textContent=error.message;install.disabled=true;}});
 install.addEventListener('click',async()=>{if(!review||!bytes)return;install.disabled=true;try{const result=await client.request('/api/packages/install',{archive_base64:bytes,expected_sha256:review.archive_sha256??review.sha256});output.textContent=JSON.stringify(result,null,2);await refresh();await onChanged();}catch(error){output.textContent=error.message;}});
 const installed=document.createElement('section');dialog.append(installed);
 async function refresh(){try{const result=await client.request('/api/packages');installed.replaceChildren();const title=document.createElement('h3');title.textContent='Installed packages';installed.append(title);for(const item of (Array.isArray(result)?result:result.packages??result.installed??[])){const row=document.createElement('div');row.className='task-actions';const label=document.createElement('span');label.textContent=`${item.package?.id??item.id}@${item.package?.version??item.version}`;const remove=document.createElement('button');remove.textContent='Uninstall';remove.addEventListener('click',async()=>{try{output.textContent=JSON.stringify(await client.request('/api/packages/uninstall',{id:item.package?.id??item.id,version:item.package?.version??item.version}),null,2);await refresh();await onChanged();}catch(error){output.textContent=error.message;}});row.append(label,remove);installed.append(row);
 for(const path of Object.keys(item.package?.files??{})){const entry=document.createElement('div');entry.className='task-actions';const filename=document.createElement('span');filename.textContent=path;const read=async()=>{const response=await client.response('/api/packages/file',{id:item.package.id,version:item.package.version,path,expected_sha256:item.sha256});const size=Number(response.headers.get('Content-Length'));return boundedResponseBytes(response,size,64*1024*1024);};const download=document.createElement('button');download.textContent='Download / 下载';download.setAttribute('aria-label','Download '+path);download.addEventListener('click',async()=>{try{const bytes=await read(),url=URL.createObjectURL(new Blob([bytes]));const a=document.createElement('a');a.href=url;a.download=path.split('/').at(-1);a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){output.textContent=error.message;}});entry.append(filename,download);
 if(path.endsWith('.json')){const use=document.createElement('button');use.textContent='Review import / 预览导入';use.setAttribute('aria-label','Import '+path);use.addEventListener('click',async()=>{try{const bytes=await read();if(bytes.byteLength>10*1024*1024)throw Error('JSON import exceeds 10 MiB');const value=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));const kind=value.assembly_version?'assembly':value.workspace_format_version||value.project_version?'project':null;if(!kind)throw Error('Only project/workspace or assembly JSON can be imported; other data can be downloaded');reviewTransaction({title:'Import '+path,description:kind==='assembly'?'Validate and add to the local mechanism library. It will not be applied automatically.':'Open this project in the editor. The current draft is retained in Recent projects. No run will be submitted.',rows:[item.package.id+'@'+item.package.version,'SHA-256 '+item.sha256,kind+': '+(value.id??value.project?.id??'')],commit:async()=>{await onImport(value,kind);dialog.close();return true;}});}catch(error){output.textContent=error.message;}});entry.append(use);}installed.append(entry);
 }}}catch(error){output.textContent=error.message;}}
 const requirements=document.createElement('textarea');requirements.value='{}';requirements.setAttribute('aria-label','Exact package requirements JSON');dialog.append(requirements);
 const resolve=document.createElement('button');resolve.textContent='Resolve and pin project lock / 解析项目锁';resolve.addEventListener('click',async()=>{try{const values=JSON.parse(requirements.value);const result=await client.request('/api/packages/resolve',{requirements:values,...(pinId?{pin_id:pinId}:{})});output.textContent=JSON.stringify(result,null,2);await onLock(result);}catch(error){output.textContent=error.message;}});dialog.append(resolve);
 const close=document.createElement('button');close.textContent='Close / 关闭';close.addEventListener('click',()=>dialog.close());dialog.append(close);dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal();refresh();
}
